### ISSUE TITLE
ZST's after version 1.0.2 won't decompress

### ISSUE THREAD

**Issue by Bri1101** [PhoenixICE/MarioKartTour-Zst_Decompress#2]
The .zst files that I tried to decompress won't decompress because the files came from newer versions. Can you update it?

**Comment by awesomebytes** [comment]
May I add, how did you get/create/generate 1.0.2.zdict?

**Comment by PhoenixICE** [comment]
Sorry I no longer play this game so I won't be updating the zdict.
To obtain the latest zdict you'll need to dump it during runtime.

**Comment by Fevirre** [comment]
> Sorry I no longer play this game so I won't be updating the zdict. To obtain the latest zdict you'll need to dump it during runtime.

What do you mean by runtime? And if so which program?

**Comment by PhoenixICE** [comment]
> > Sorry I no longer play this game so I won't be updating the zdict. To obtain the latest zdict you'll need to dump it during runtime.
> 
> What do you mean by runtime? And if so which program?

Runtime = when the program is running
Which Program = Something you'll have to research this isn't a single program that does this and requires knowledge on how to hook into running apps and navigating memory addresses and virtual functions etc...there isn't a program you just download and it does it for you, you'll have to code it.
